import manifest from '../data/image-manifest.json'

/** Looks up an optimized image generated by `npm run images`. */
export function getImage(imageKey) {
  return imageKey ? (manifest[imageKey] ?? null) : null
}

export function hasImage(imageKey) {
  return Boolean(getImage(imageKey))
}
