import { getImage } from '../../utils/images.js'

/**
 * Renders an optimized image from `src/data/image-manifest.json`
 * (generated by `npm run images`) with srcset, intrinsic size and lazy
 * loading. `imageKey` is the file path inside `images-source/` without
 * its extension, e.g. "flavors/matcha-calamansi".
 */
export default function ResponsiveImage({
  imageKey,
  alt,
  sizes = '100vw',
  loading = 'lazy',
  fetchPriority,
  className,
  ...rest
}) {
  const entry = getImage(imageKey)

  if (!entry) {
    if (import.meta.env.DEV && imageKey) {
      console.warn(`[ResponsiveImage] "${imageKey}" is not in the image manifest. Run "npm run images".`)
    }
    return null
  }

  const largest = entry.variants[entry.variants.length - 1]
  const srcSet = entry.variants.map((v) => `${v.src} ${v.width}w`).join(', ')

  return (
    <img
      src={largest.src}
      srcSet={srcSet}
      sizes={sizes}
      width={entry.width}
      height={entry.height}
      alt={alt}
      loading={loading}
      decoding="async"
      fetchPriority={fetchPriority}
      className={className}
      {...rest}
    />
  )
}
